---
- hosts: all
  vars:
    repos: [
      "https://github.com/hugsy/gef.git",
      "https://github.com/groldo/dotfiles.git"
    ]
    packages: [
      "texlive-latex-extra",
      "texlive-fonts-extra",
      "texlive-lang-german",
      "pandoc",
      "gdb",
      "vim",
      "tmux"
    ]
  tasks:
    - name: install latest packages
      become: yes
      apt:
        name: "*"
        state: latest
        force_apt_get: true
        update_cache: yes

    - name: Install a list of packages
      become: yes
      apt:
        name: "{{ item }}"
        autoclean: yes
        autoremove: yes
      loop: "{{ packages }}"
      when: packages|length > 0

    - name: Prepare some git repos
      git:
        repo: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.git_repos/"
      loop: "{{ repos }}"
      when: repos|length > 0

  roles:
    - role: docker-role
      vars: 
        docker_users: ["vagrant"]

